version: '3.8' # Use a recent version

services:
  auth_api:
    build:
      context: .
      ssh: ["default"]
    container_name: soaricarus_auth
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      auth_db:
        condition: service_healthy
    restart: unless-stopped

  auth_db:
    image: postgres:18.4-alpine
    container_name: soaricarus_auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER:-soaricarus_op}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_AUTH_DB:-soaricarus_auth_db}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
        # Checks if Postgres is ready to accept connections
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
    restart: always

volumes:
  postgres_data:
    driver: local # Use the default local driver
